# Generated by fixnix at 2020-04-29
# $ fixnix --repo=ucla-pls/reduce --branch=logic --no-import
builtins.fetchTarball {
  name   = "reduce_logic_205b9c";
  url    = "https://github.com/ucla-pls/reduce/archive/205b9c857667ef5ad0413f21744cc9ba670d43f7.tar.gz";
  sha256 = "1invj9a38pwc45yagav97a9ja1b233k74anffwa0035chpk0ngdh";
}
