# Generated by fixnix on 2020-04-29
# $ fixnix --repo=ucla-pls/reduce --branch=logic --no-import
builtins.fetchTarball {
  name   = "reduce_logic_5e2760";
  url    = "https://github.com/ucla-pls/reduce/archive/5e2760b0908f77a41b2535ac1b51d0f38119a72e.tar.gz";
  sha256 = "0wxn0mjypkizw1zif56pd5bl5wqr37kp5lca4i8g9k58nqgis4ry";
}
