# Generated by fixnix on 2020-04-29
# $ fixnix --hackage=dirtree-0.1.3 --no-import
builtins.fetchTarball {
  name   = "dirtree-0.1.3";
  url    = "https://hackage.haskell.org/package/dirtree-0.1.3/dirtree-0.1.3.tar.gz";
  sha256 = "0kl31l2ip856saq5lhfjr4wv04i2pyj6sf3lkzk9bj7w1m9v0klz";
}
